---

- hosts :
    - all
  become: true
  become_user: root
  become_method: su
  gather_facts: false

  vars:
    Your_Name1: Sheikh Sami Ahmed
    YOUR_NAME2: Salman Arif
    YOUR_NAME3: Sufiyan
  
  tasks:

    - name:  Add text "This is third file made by your name in test3.txt."
      ansible.builtin.lineinfile:
        path: /root/TEST/test03.txt
        line: "This is third file made by {{ YOUR_NAME3 }}"
      delegate_to: localhost
 

    

    