
---

- hosts :
    - all
  become: true
  become_user: root
  become_method: su
  gather_facts: false

  vars:
    count: 0
    Your_Name1: Sheikh Sami Ahmed
    YOUR_NAME2: Salman Arif
    YOUR_NAME3: Sufiyan
  

  tasks:
    - name: Add text "This is second file made by YOUR NAME in test2.txt."
      ansible.builtin.lineinfile:
        path: /root/TEST/test02.txt
        line: "This is second file made by {{ YOUR_NAME2 }}"
      delegate_to: localhost




