---

- hosts :
    - all
  become: true
  become_user: root
  become_method: su
  gather_facts: false

  tasks:

    - name: Make ssh connection remote host
      shell: >
        sshpass -p {{ansible_password}} ssh -o "StrictHostKeyChecking no" {{ansible_user}}@{{ansible_host}}
      delegate_to: localhost
      become: false  

    
    - name: Unzip the archived folder on current location.
      become: true
      become_user: root
      ansible.builtin.unarchive:
        src: /root/allfiles.tar.bz2
        dest: /root
        remote_src: yes